### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by chinnaiyanvignesh** [lucatacconi/crunz-ui#11]
**To Reproduce**

When we run a command : `vendor/bin/crunz schedule:list`, we are getting the error pasted below.

**Expected behavior**
```
 [Deprecation] Method 'everyTwelveHours' is deprecated since v2.3, use 'cron'
               method instead. File
               /var/www/html/crunz-ui/vendor/lavary/crunz/src/Event.php, line
               217
```

**Screenshots**
![image](https://user-images.githubusercontent.com/46555633/129524439-fcc80b33-fd0b-456f-8bf2-02486211aceb.png)

**Comment by lucatacconi** [comment]
Thanks Chinnaiyanvignesh, we had already seen the notice on the library. 

We are working on a global update of Crunz-ui which will be released in a couple of weeks. Please stay up to date and update Crunz-ui as soon as the new version is released.

However, I will update you as soon as the new version is released

**Comment by chinnaiyanvignesh** [comment]
Hi Lucatacconi,

Thanks for the update.
