### ISSUE TITLE
Engine Error: Error - Task execution Error - Related to Logs All Settings appear correct

### ISSUE THREAD

**Issue by clwehunt** [lucatacconi/crunz-ui#9]
**Describe the bug**
When attempting to run a task manually, the following error is shown:
Engine Error: Error - Task execution Error 

**To Reproduce**
1. Go to 'Tasks table'
2. Click on '...'
3. Click on 'Execute and wait log'
4. See the error (see below for screenshots)

**Expected behavior**
I would expect the task to run and show the log, or at least show the task ran successfully or indicate if there were any errors.

**Screenshots**
Screenshot of Error:
![image](https://user-images.githubusercontent.com/41650086/126822884-6f2a418d-86c9-438f-9f72-b9e9067e3440.png)

Screenshot Confirming that the Log file directories and settings all check out:
![image](https://user-images.githubusercontent.com/41650086/126822904-1715fe47-49bf-4578-8d53-35493147b53f.png)

**Desktop (please complete the following information):**
 - OS: Mac Catalina 
 - Browser Chrome
 - Version 91.0.4472.164

**Additional context**
The error is generated by the following block in task.php. 

if(empty($log_file_name)){
    throw new Exception("ERROR - Task execution error");
}

**Comment by lucatacconi** [comment]
Hi Clwehunt, 
sorry for the delay
have you installed Crunz-ui on your machine or on a virtual machine?
is Crunz-ui served by Apache server or Xampp?
If you are using Xampp do you have a PHP installed on your machine too?

**Comment by lucatacconi** [comment]
While I wait for your answer I can tell you i encountered a similar error when i used Crunz-ui delivered by Xampp while i had Apache and PHP installed on the same machine.

in the situation above, Web interface in fact is served by Xampp Apache and PHP but scheduled task execution is executed by PHP installed in the machine. When you try to start execution by web interface Xampp try to use PHP installed on the same machine with modules and libraries installed in Xampp end obviously get an error.

Mc systems are derived from linux systems, so the solution I am about to propose could work there too
You can avoid error replacing the php symlink in the /usr/bin directory and pointing it to Xampp's php.

**Do not delete the original symbolic link but save or rename it**
